## ---------- ##
## Containers ##
## ---------- ##
r_container: "docker://rtpop/process_cel:0.9"

## Number of cores
ncores: 30

## Directories

src_dir: "src" # Code directory
data_dir: "data"
raw_data_dir: "data/raw_data"
processed_data_dir: "data/processed_data"

# Run ID
run_tag: "matched"

## ----------- ##
## Input files ##
## ----------- ##
metadata_file: "all_primary_samples_msi.csv"


## ----------------- ##
## Processing params ##
## ----------------- ##

# Which files to select for processing
# in case different batches of files need different processing (i.e. different batch correction, etc)
# options: "all", "multi_region", "single_region"
processing_cel: FALSE
file_selection_method: "all" # all | multi_region | single_region
normal_samples: FALSE # whether to include normal samples in the processing
array_type: "hta20" # type of array: supported: hta20 | huex10 (case insensitive)
batch_correction: TRUE # whether to perform batch correction
batch_metadata_column: "Array" # column name in the metadata file indicating batches
normalise: TRUE # whether to normalise the data
background_correction: TRUE # whether to perform background correction
background_correction_method: "rma" # method for background correction
normalization_method: "quantile" # method for normalization
average_by_tumour: FALSE # whether to average expression values by tumour
compile_datasets: TRUE # whether to compile multiple datasets into a single expression matrix
datasets_to_compile: ["hta_all_exp_batch_corrected.txt", "huex_all_exp.txt"] # list of filenames of datasets to compile if compile_datasets is TRUE. These should be in processed_data_dir
tumour_metadata_column: HTA_sample_file_name # column name in the metadata file indicating tumour IDs for averaging

## PCA params ##
pca_color_by: "Array" # column name in the metadata file to color points by
pca_shape_by: NULL # column name in the metadata file to shape points by
pca_title: "PCA of merged hta + huex" # title of the PCA plot
top_n: FALSE
n_probes: 1000

## ------------ ##
## Output files ##
## ------------ ##

exp_file: "merged_exp.txt"
exp_file_batch_corrected: "merged_exp_batch_corrected.txt"
exp_file_final: "merged_exp_final.txt"
exp_file_avg: "merged_exp_avg_by_tumour.txt"