## ---------- ##
## Containers ##
## ---------- ##
r_container: "docker://rtpop/process_cel:0.9"

## Number of cores
ncores: 30

## Directories

src_dir: "src" # Code directory
data_dir: "data"
raw_data_dir: "data/raw_data"
processed_data_dir: "data/processed_data"

# Run ID
run_tag: "matched"

## ----------- ##
## Input files ##
## ----------- ##
metadata_file: "matched_microarray_metadata.csv"
cel_files: "matched_raw_data_files.txt" # text file with list of raw data files (CEL files) to process (one file per line)

## ----------------- ##
## Processing params ##
## ----------------- ##

# Which files to select for processing
# in case different batches of files need different processing (i.e. different batch correction, etc)
# options: "all", "multi_region", "single_region"
processing_cel: true
file_selection_method: "all" # all | multi_region | single_region
normal_samples: FALSE # whether to include normal samples in the processing
array_type: "hta20" # type of array: supported: hta20 | huex10 (case insensitive)
batch_correction: FALSE # whether to perform batch correction
batch_metadata_column: "" # column name in the metadata file indicating batches
normalise: TRUE # whether to normalise the data
background_correction: TRUE # whether to perform background correction
background_correction_method: "rma" # method for background correction
normalization_method: "quantile" # method for normalization
average_by_tumour: TRUE # whether to average expression values by tumour
compile_datasets: FALSE # whether to compile multiple datasets into a single expression matrix
datasets_to_compile: [] # list of filenames of datasets to compile if compile_datasets is TRUE. These should be in processed_data_dir
tumour_metadata_column: HTA_sample_file_name # column name in the metadata file indicating tumour IDs for averaging

## PCA params ##
pca_color_by: "Tissue" # column name in the metadata file to color points by
pca_shape_by: NULL # column name in the metadata file to shape points by
pca_title: "PCA of Matched Samples" # title of the PCA plot
top_n: FALSE
n_probes: 1000

## ------------ ##
## Output files ##
## ------------ ##

exp_file: "matched_exp_all_smpl.txt"
exp_file_batch_corrected: "matched_exp_batch_corrected.txt"
exp_file_final: "matched_exp_final.txt"
exp_file_avg: "matched_exp_avg_by_tumour.txt"